services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/miniProjectDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Zekiye.26
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: miniProjectDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zekiye.26
      PGDATA: /var/lib/postgresql/data
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
        - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
